// 日本の都道府県（JIS X 0401 順）。エリア入力のプルダウンと表記分解に使う。
// 市区町村は数が多く変化もあるため静的には持たず、/api/cities（HeartRails Geo API経由）で取得する。
export const PREFECTURES = [
  "北海道",
  "青森県",
  "岩手県",
  "宮城県",
  "秋田県",
  "山形県",
  "福島県",
  "茨城県",
  "栃木県",
  "群馬県",
  "埼玉県",
  "千葉県",
  "東京都",
  "神奈川県",
  "新潟県",
  "富山県",
  "石川県",
  "福井県",
  "山梨県",
  "長野県",
  "岐阜県",
  "静岡県",
  "愛知県",
  "三重県",
  "滋賀県",
  "京都府",
  "大阪府",
  "兵庫県",
  "奈良県",
  "和歌山県",
  "鳥取県",
  "島根県",
  "岡山県",
  "広島県",
  "山口県",
  "徳島県",
  "香川県",
  "愛媛県",
  "高知県",
  "福岡県",
  "佐賀県",
  "長崎県",
  "熊本県",
  "大分県",
  "宮崎県",
  "鹿児島県",
  "沖縄県",
] as const;

/** 「大阪府堺市北区」→ { pref: "大阪府", city: "堺市北区" }。都道府県が判定できなければ pref="" */
export function splitArea(area: string): { pref: string; city: string } {
  const pref = PREFECTURES.find((p) => area.startsWith(p)) ?? "";
  return { pref, city: pref ? area.slice(pref.length) : area };
}
